import BrazilFlag from '../../assets/images/brazil.png';
import ChinaFlag from '../../assets/images/china.png';
import GermanyFlag from '../../assets/images/germany.png';
import ItalyFlag from '../../assets/images/italy.png';
import UsaFlag from '../../assets/images/usa.png';

const COUNTRIES = [
  {
    label: 'Alemanha',
    value: 'germany',
    flag: GermanyFlag,
  },
  {
    label: 'Brasil',
    value: 'brazil',
    flag: BrazilFlag,
  },
  {
    label: 'China',
    value: 'china',
    flag: ChinaFlag,
  },
  {
    label: 'Estados Unidos',
    value: 'usa',
    flag: UsaFlag,
  },
  {
    label: 'Itália',
    value: 'italy',
    flag: ItalyFlag,
  },
];
export const countries = [
  { id: 1, label: 'AFEGANISTÃO', value: 'AFGHANISTAN' },
  { id: 2, label: 'ACROTÍRI E DECELIA', value: 'AKROTIRI E DEKÉLIA' },
  { id: 3, label: 'ÁFRICA DO SUL', value: 'SOUTH AFRICA' },
  { id: 4, label: 'ALBÂNIA', value: 'ALBANIA' },
  { id: 5, label: 'ALEMANHA', value: 'GERMANY' },
  { id: 6, label: 'AMERICAN SAMOA', value: 'AMERICAN SAMOA' },
  { id: 7, label: 'ANDORRA', value: 'ANDORRA' },
  { id: 8, label: 'ANGOLA', value: 'ANGOLA' },
  { id: 9, label: 'ANGUILLA', value: 'ANGUILLA' },
  { id: 10, label: 'ANTILHAS NEERLANDESAS', value: 'NETHERLANDS ANTILLES' },
  { id: 12, label: 'ARÁBIA SAUDITA', value: 'SAUDI ARABIA' },
  { id: 13, label: 'ARGÉLIA', value: 'ALGERIA' },
  { id: 14, label: 'ARGENTINA', value: 'ARGENTINA' },
  { id: 15, label: 'ARMÉNIA', value: 'ARMENIA' },
  { id: 16, label: 'ARUBA', value: 'ARUBA' },
  { id: 17, label: 'AUSTRÁLIA', value: 'AUSTRALIA' },
  { id: 18, label: 'ÁUSTRIA', value: 'AUSTRIA' },
  { id: 19, label: 'AZERBAIJÃO', value: 'AZERBAIJAN' },
  { id: 20, label: 'BAHAMAS', value: 'BAHAMAS, THE' },
  { id: 21, label: 'BANGLADECHE', value: 'BANGLADESH' },
  { id: 22, label: 'BARBADOS', value: 'BARBADOS' },
  { id: 23, label: 'BARÉM', value: 'BAHRAIN' },
  { id: 24, label: 'BASSAS DA ÍNDIA', value: 'BASSAS DA INDIA' },
  { id: 25, label: 'BÉLGICA', value: 'BELGIUM' },
  { id: 26, label: 'BENIM', value: 'BENIN' },
  { id: 28, label: 'BERMUDAS', value: 'BERMUDA' },
  { id: 29, label: 'BIELORRÚSSIA', value: 'BELARUS' },
  { id: 30, label: 'BOLÍVIA', value: 'BOLIVIA' },
  { id: 31, label: 'BOTSUANA', value: 'BOTSWANA' },
  { id: 33, label: 'BRASIL', value: 'BRAZIL' },
  { id: 34, label: 'BRUNEI DARUSSALAM', value: 'BRUNEI DARUSSALAM' },
  { id: 35, label: 'BULGÁRIA', value: 'BULGARIA' },
  { id: 36, label: 'BURQUINA FASO', value: 'BURKINA FASO' },
  { id: 37, label: 'BURUNDI', value: 'BURUNDI' },
  { id: 38, label: 'BUTÃO', value: 'BHUTAN' },
  { id: 39, label: 'CABO VERDE', value: 'CAPE VERDE' },
  { id: 40, label: 'CAMARÕES', value: 'CAMEROON' },
  { id: 41, label: 'CAMBOJA', value: 'CAMBODIA' },
  { id: 42, label: 'CANADÁ', value: 'CANADA' },
  { id: 43, label: 'CATAR', value: 'QATAR' },
  { id: 44, label: 'CAZAQUISTÃO', value: 'KAZAKHSTAN' },
  {
    id: 45,
    label: 'CENTRO-AFRICANA REPÚBLICA',
    value: 'CENTRAL AFRICAN REPUBLIC',
  },
  { id: 46, label: 'CHADE', value: 'CHAD' },
  { id: 47, label: 'CHILE', value: 'CHILE' },
  { id: 48, label: 'CHINA', value: 'CHINA' },
  { id: 49, label: 'CHIPRE', value: 'CYPRUS' },
  { id: 50, label: 'COLÔMBIA', value: 'COLOMBIA' },
  { id: 51, label: 'COMORES', value: 'COMOROS' },
  { id: 52, label: 'CONGO', value: 'CONGO' },
  {
    id: 53,
    label: 'CONGO REPÚBLICA DEMOCRÁTICA',
    value: 'CONGO DEMOCRATIC REPUBLIC',
  },
  { id: 54, label: 'COREIA DO NORTE', value: 'KOREA NORTH' },
  { id: 55, label: 'COREIA DO SUL', value: 'KOREA SOUTH' },
  { id: 56, label: 'COSTA DO MARFIM', value: 'IVORY COAST' },
  { id: 57, label: 'COSTA RICA', value: 'COSTA RICA' },
  { id: 58, label: 'CROÁCIA', value: 'CROATIA' },
  { id: 59, label: 'CUBA', value: 'CUBA' },
  { id: 60, label: 'DINAMARCA', value: 'DENMARK' },
  { id: 61, label: 'DOMÍNICA', value: 'DOMINICA' },
  { id: 62, label: 'EGIPTO', value: 'EGYPT' },
  { id: 63, label: 'EMIRADOS ÁRABES UNIDOS', value: 'UNITED ARAB EMIRATES' },
  { id: 64, label: 'EQUADOR', value: 'ECUADOR' },
  { id: 65, label: 'ERITREIA', value: 'ERITREA' },
  { id: 66, label: 'ESLOVÁQUIA', value: 'SLOVAKIA' },
  { id: 67, label: 'ESLOVÉNIA', value: 'SLOVENIA' },
  { id: 68, label: 'ESPANHA', value: 'SPAIN' },
  { id: 69, label: 'ESTADOS UNIDOS', value: 'UNITED STATES' },
  { id: 70, label: 'ESTÓNIA', value: 'ESTONIA' },
  { id: 71, label: 'ETIÓPIA', value: 'ETHIOPIA' },
  { id: 72, label: 'FAIXA DE GAZA', value: 'GAZA STRIP' },
  { id: 73, label: 'FIJI', value: 'FIJI' },
  { id: 74, label: 'FILIPINAS', value: 'PHILIPPINES' },
  { id: 75, label: 'FINLÂNDIA', value: 'FINLAND' },
  { id: 76, label: 'FRANÇA', value: 'FRANCE' },
  { id: 77, label: 'GABÃO', value: 'GABON' },
  { id: 78, label: 'GÂMBIA', value: 'GAMBIA' },
  { id: 79, label: 'GANA', value: 'GHANA' },
  { id: 80, label: 'GEÓRGIA', value: 'GEORGIA' },
  { id: 81, label: 'GIBRALTAR', value: 'GIBRALTAR' },
  { id: 82, label: 'GRONELÂNDIA', value: 'GREENLAND' },
  { id: 85, label: 'GUADALUPE', value: 'GUADELOUPE' },
  { id: 86, label: 'GUAM', value: 'GUAM' },
  { id: 87, label: 'GUATEMALA', value: 'GUATEMALA' },
  { id: 88, label: 'GUERNSEY', value: 'GUERNSEY' },
  { id: 89, label: 'GUIANA', value: 'GUYANA' },
  { id: 90, label: 'GUIANA FRANCESA', value: 'FRENCH GUIANA' },
  { id: 91, label: 'GUINÉ', value: 'GUINEA' },
  { id: 92, label: 'GUINÉ EQUATORIAL', value: 'EQUATORIAL GUINEA' },
  { id: 93, label: 'GUINÉ-BISSAU', value: 'GUINEA-BISSAU' },
  { id: 94, label: 'HAITI', value: 'HAITI' },
  { id: 95, label: 'HONDURAS', value: 'HONDURAS' },
  { id: 96, label: 'HONG KONG', value: 'HONG KONG' },
  { id: 97, label: 'HUNGRIA', value: 'HUNGARY' },
  { id: 98, label: 'IÉMEN', value: 'YEMEN' },
  { id: 99, label: 'ILHA BOUVET', value: 'BOUVET ISLAND' },
  { id: 100, label: 'ILHA CHRISTMAS', value: 'CHRISTMAS ISLAND' },
  { id: 101, label: 'ILHA DE CLIPPERTON', value: 'CLIPPERTON ISLAND' },
  { id: 102, label: 'ILHA DE JOÃO DA NOVA', value: 'JUAN DE NOVA ISLAND' },
  { id: 103, label: 'ILHA DE MAN', value: 'ISLE OF MAN' },
  { id: 104, label: 'ILHA DE NAVASSA', value: 'NAVASSA ISLAND' },
  { id: 105, label: 'ILHA EUROPA', value: 'EUROPA ISLAND' },
  { id: 106, label: 'ILHA NORFOLK', value: 'NORFOLK ISLAND' },
  { id: 107, label: 'ILHA TROMELIN', value: 'TROMELIN ISLAND' },
  {
    id: 108,
    label: 'ILHAS ASHMORE E CARTIER',
    value: 'ASHMORE AND CARTIER ISLANDS',
  },
  { id: 109, label: 'ILHAS CAIMAN', value: 'CAYMAN ISLANDS' },
  {
    id: 110,
    label: 'ILHAS COCOS {id: KEELING}',
    value: 'COCOS {id: KEELING} ISLANDS',
  },
  { id: 111, label: 'ILHAS COOK', value: 'COOK ISLANDS' },
  { id: 112, label: 'ILHAS DO MAR DE CORAL', value: 'CORAL SEA ISLANDS' },
  { id: 113, label: 'ILHAS MALVINAS', value: 'FALKLAND ISLANDS }' },
  { id: 114, label: 'ILHAS FEROE', value: 'FAROE ISLANDS' },
  {
    id: 115,
    label: 'ILHAS GEÓRGIA DO SUL E SANDWICH DO SUL',
    value: 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS',
  },
  {
    id: 116,
    label: 'ILHAS MARIANAS DO NORTE',
    value: 'NORTHERN MARIANA ISLANDS',
  },
  { id: 117, label: 'ILHAS MARSHALL', value: 'MARSHALL ISLANDS' },
  { id: 117, label: 'ILHAS MARSHALL', value: 'MARSHALL ISLANDS' },
  { id: 118, label: 'ILHAS PARACEL', value: 'PARACEL ISLANDS' },
  { id: 119, label: 'ILHAS PITCAIRN', value: 'PITCAIRN ISLANDS' },
  { id: 120, label: 'ILHAS SALOMÃO', value: 'SOLOMON ISLANDS' },
  { id: 121, label: 'ILHAS SPRATLY', value: 'SPRATLY ISLANDS' },
  {
    id: 122,
    label: 'ILHAS VIRGENS AMERICANAS',
    value: 'UNITED STATES VIRGIN ISLANDS',
  },
  {
    id: 123,
    label: 'ILHAS VIRGENS BRITÂNICAS',
    value: 'BRITISH VIRGIN ISLANDS',
  },
  { id: 124, label: 'ÍNDIA', value: 'INDIA' },
  { id: 125, label: 'INDONÉSIA', value: 'INDONESIA' },
  { id: 126, label: 'IRÃO', value: 'IRAN' },
  { id: 127, label: 'IRAQUE', value: 'IRAQ' },
  { id: 128, label: 'IRLANDA', value: 'IRELAND' },
  { id: 129, label: 'ISLÂNDIA', value: 'ICELAND' },
  { id: 130, label: 'JAMAICA', value: 'JAMAICA' },
  { id: 133, label: 'JAN MAYEN', value: 'JAN MAYEN' },
  { id: 134, label: 'JAPÃO', value: 'JAPAN' },
  { id: 135, label: 'JERSEY', value: 'JERSEY' },
  { id: 136, label: 'JIBUTI', value: 'DJIBOUTI' },
  { id: 137, label: 'JORDÂNIA', value: 'JORDAN' },
  { id: 138, label: 'KIRIBATI', value: 'KIRIBATI' },
  { id: 139, label: 'KOWEIT', value: 'KUWAIT' },
  { id: 140, label: 'LAOS', value: 'LAOS' },
  { id: 141, label: 'LESOTO', value: 'LESOTHO' },
  { id: 142, label: 'LETÓNIA', value: 'LATVIA' },
  { id: 143, label: 'LÍBANO', value: 'LEBANON' },
  { id: 144, label: 'LIBÉRIA', value: 'LIBERIA' },
  { id: 145, label: 'LÍBIA', value: 'LIBYAN ARAB JAMAHIRIYA' },
  { id: 146, label: 'LISTENSTAINE', value: 'LIECHTENSTEIN' },
  { id: 147, label: 'LITUÂNIA', value: 'LITHUANIA' },
  { id: 148, label: 'LUXEMBURGO', value: 'LUXEMBOURG' },
  { id: 149, label: 'MACAU', value: 'MACAO' },
  { id: 150, label: 'MACEDÓNIA', value: 'MACEDONIA' },
  { id: 151, label: 'MADAGÁSCAR', value: 'MADAGASCAR' },
  { id: 152, label: 'MALÁSIA', value: 'MALAYSIA' },
  { id: 153, label: 'MALAVI', value: 'MALAWI' },
  { id: 154, label: 'MALDIVAS', value: 'MALDIVES' },
  { id: 155, label: 'MALI', value: 'MALI' },
  { id: 156, label: 'MALTA', value: 'MALTA' },
  { id: 157, label: 'MARROCOS', value: 'MOROCCO' },
  { id: 158, label: 'MARTINICA', value: 'MARTINIQUE' },
  { id: 159, label: 'MAURÍCIA', value: 'MAURITIUS' },
  { id: 160, label: 'MAURITÂNIA', value: 'MAURITANIA' },
  { id: 161, label: 'MAYOTTE', value: 'MAYOTTE' },
  { id: 162, label: 'MÉXICO', value: 'MEXICO' },
  { id: 163, label: 'MIANMAR', value: 'MYANMAR BURMA' },
  { id: 164, label: 'MICRONÉSIA', value: 'MICRONESIA' },
  { id: 165, label: 'MOÇAMBIQUE', value: 'MOZAMBIQUE' },
  { id: 166, label: 'MOLDÁVIA', value: 'MOLDOVA' },
  { id: 167, label: 'MÓNACO', value: 'MONACO' },
  { id: 168, label: 'MONGÓLIA', value: 'MONGOLIA' },
  { id: 169, label: 'NAMÍBIA', value: 'NAMIBIA' },
  { id: 172, label: 'NAURU', value: 'NAURU' },
  { id: 173, label: 'NEPAL', value: 'NEPAL' },
  { id: 174, label: 'NICARÁGUA', value: 'NICARAGUA' },
  { id: 175, label: 'NÍGER', value: 'NIGER' },
  { id: 176, label: 'NIGÉRIA', value: 'NIGERIA' },
  { id: 177, label: 'NIUE', value: 'NIUE' },
  { id: 178, label: 'NORUEGA', value: 'NORWAY' },
  { id: 179, label: 'NOVA CALEDÓNIA', value: 'NEW CALEDONIA' },
  { id: 180, label: 'NOVA ZELÂNDIA', value: 'NEW ZEALAND' },
  { id: 181, label: 'OMÃ', value: 'OMAN' },
  { id: 182, label: 'PAÍSES BAIXOS', value: 'NETHERLANDS' },
  { id: 183, label: 'PALAU', value: 'PALAU' },
  { id: 184, label: 'PALESTINA', value: 'PALESTINE' },
  { id: 185, label: 'PANAMÁ', value: 'PANAMA' },
  { id: 186, label: 'PAPUÁSIA-NOVA GUINÉ', value: 'PAPUA NEW GUINEA' },
  { id: 187, label: 'PAQUISTÃO', value: 'PAKISTAN' },
  { id: 188, label: 'PARAGUAI', value: 'PARAGUAY' },
  { id: 189, label: 'PERU', value: 'PERU' },
  { id: 190, label: 'POLINÉSIA FRANCESA', value: 'FRENCH POLYNESIA' },
  { id: 191, label: 'POLÓNIA', value: 'POLAND' },
  { id: 192, label: 'PORTO RICO', value: 'PUERTO RICO' },
  { id: 193, label: 'PORTUGAL', value: 'PORTUGAL' },
  { id: 194, label: 'QUÉNIA', value: 'KENYA' },
  { id: 195, label: 'QUIRGUIZISTÃO', value: 'KYRGYZSTAN' },
  { id: 196, label: 'REINO UNIDO', value: 'UNITED KINGDOM' },
  { id: 197, label: 'REPÚBLICA CHECA', value: 'CZECH REPUBLIC' },
  { id: 198, label: 'REPÚBLICA DOMINICANA', value: 'DOMINICAN REPUBLIC' },
  { id: 199, label: 'ROMÉNIA', value: 'ROMANIA' },
  { id: 200, label: 'RUANDA', value: 'RWANDA' },
  { id: 201, label: 'RÚSSIA', value: 'RUSSIAN FEDERATION' },
  { id: 202, label: 'SAHARA OCCIDENTAL', value: 'WESTERN SAHARA' },
  { id: 203, label: 'SALVADOR', value: 'EL SALVADOR' },
  { id: 204, label: 'SAMOA', value: 'SAMOA' },
  { id: 205, label: 'SANTA HELENA', value: 'SAINT HELENA' },
  { id: 206, label: 'SANTA LÚCIA', value: 'SAINT LUCIA' },
  { id: 207, label: 'SANTA SÉ', value: 'HOLY SEE' },
  { id: 208, label: 'SÃO CRISTÓVÃO E NEVES', value: 'SAINT KITTS AND NEVIS' },
  { id: 209, label: 'SÃO MARINO', value: 'SAN MARINO' },
  {
    id: 210,
    label: 'SÃO PEDRO E MIQUELÃO',
    value: 'SAINT PIERRE AND MIQUELON',
  },
  { id: 211, label: 'SÃO TOMÉ E PRÍNCIPE', value: 'SAO TOME AND PRINCIPE' },
  {
    id: 212,
    label: 'SÃO VICENTE E GRANADINAS',
    value: 'SAINT VINCENT AND THE GRENADINES',
  },
  { id: 213, label: 'SEICHELES', value: 'SEYCHELLES' },
  { id: 214, label: 'SENEGAL', value: 'SENEGAL' },
  { id: 215, label: 'SERRA LEOA', value: 'SIERRA LEONE' },
  { id: 216, label: 'SÉRVIA', value: 'SERBIA' },
  { id: 217, label: 'SINGAPURA', value: 'SINGAPORE' },
  { id: 218, label: 'SÍRIA', value: 'SYRIA' },
  { id: 219, label: 'SOMÁLIA', value: 'SOMALIA' },
  { id: 220, label: 'SRI LANCA', value: 'SRI LANKA' },
  { id: 221, label: 'SUAZILÂNDIA', value: 'SWAZILAND' },
  { id: 222, label: 'SUDÃO', value: 'SUDAN' },
  { id: 223, label: 'SUÉCIA', value: 'SWEDEN' },
  { id: 224, label: 'SUÍÇA', value: 'SWITZERLAND' },
  { id: 225, label: 'SURINAME', value: 'SURINAME' },
  { id: 226, label: 'SVALBARD', value: 'SVALBARD' },
  { id: 227, label: 'TAIWAN', value: 'TAIWAN' },
  { id: 229, label: 'TAJIQUISTÃO', value: 'TAJIKISTAN' },
  { id: 230, label: 'TANZÂNIA', value: 'TANZANIA' },
  {
    id: 231,
    label: 'TERRITÓRIO BRITÂNICO DO OCEANO ÍNDICO',
    value: 'BRITISH INDIAN OCEAN TERRITORY',
  },
  {
    id: 232,
    label: 'TERRITÓRIO DAS ILHAS HEARD E MCDONALD',
    value: 'HEARD ISLAND AND MCDONALD ISLANDS',
  },
  { id: 233, label: 'TIMOR-LESTE', value: 'TIMOR-LESTE' },
  { id: 234, label: 'TOGO', value: 'TOGO' },
  { id: 235, label: 'TOKELAU', value: 'TOKELAU' },
  { id: 236, label: 'TONGA', value: 'TONGA' },
  { id: 237, label: 'TRINDADE E TOBAGO', value: 'TRINIDAD AND TOBAGO' },
  { id: 238, label: 'TUNÍSIA', value: 'TUNISIA' },
  { id: 239, label: 'TURKS E CAICOS', value: 'TURKS AND CAICOS ISLANDS' },
  { id: 240, label: 'TURQUEMENISTÃO', value: 'TURKMENISTAN' },
  { id: 241, label: 'TURQUIA', value: 'TURKEY' },
  { id: 242, label: 'TUVALU', value: 'TUVALU' },
  { id: 243, label: 'UCRÂNIA', value: 'UKRAINE' },
  { id: 244, label: 'UGANDA', value: 'UGANDA' },
  { id: 245, label: 'URUGUAI', value: 'URUGUAY' },
  { id: 246, label: 'USBEQUISTÃO', value: 'UZBEKISTAN' },
  { id: 247, label: 'VANUATU', value: 'VANUATU' },
  { id: 248, label: 'VENEZUELA', value: 'VENEZUELA' },
  { id: 249, label: 'VIETNAME', value: 'VIETNAM' },
  { id: 250, label: 'WALLIS E FUTUNA', value: 'WALLIS AND FUTUNA' },
  { id: 251, label: 'ZÂMBIA', value: 'ZAMBIA' },
  { id: 252, label: 'ZIMBABUÉ', value: 'ZIMBABWE' },
];

export default COUNTRIES;
